development:
  user: fedoraAdmin
  password: fedoraAdmin
  # url: http://127.0.0.1:<%= ENV['FCREPO_DEVELOPMENT_PORT'] || 8984 %>/rest
  url: http://172.26.0.3:8984/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://172.26.0.3<%= ENV['FCREPO_TEST_PORT'] || 8986 %>/rest
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://172.26.0.3:8983/fedora/rest
  base_path: /prod
