# This is a sample config file that points to a solr server for each environment
development:
  # url: http://127.0.0.1:<%= ENV['SOLR_TEST_PORT'] || 8983 %>/solr/hydra-development
  url:  http://localhost:8983/solr/
test:
  # url: http://127.0.0.1:<%= ENV['SOLR_TEST_PORT'] || 8985 %>/solr/hydra
  url:  http://localhost:8983/solr/
production:
  # url: http://your.production.server:8080/bl_solr/core0
  url: http://localhost:8983/solr/