version: '2'

volumes:
  fcrepo:
  solr:
  mysql:

services:
  solr:
    build:
      context: ./solr
    container_name: solr
    ports:
      - "8983:8983"
    volumes:
      - solr:/opt/solr/server/solr/mycores
      - ./solr/config:/opt/config
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - hydra
      - /opt/solr/conf
    networks:
      - backend

  fedora:
    build: ./fcrepo
    container_name: fedora
    ports:
      - "8984:8984"
    volumes:
      - fcrepo:/opt/fcrepo/data
    networks:
      - backend
  db:
    image: mysql:5.7.16
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - frontend
  hydra:
    build: .
    container_name: hydratest
    command:  bash -c "bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./hydra:/home/hydra
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - frontend
      - backend


networks:
  frontend: 
  backend: