source 'https://rubygems.org'

# Rails Dependencies
# =====================================================
gem 'rails'
gem 'bundler'
gem 'rake'
gem 'mysql2', '>= 0.3.13', '< 0.5'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

# Hydra Dependencies
# =====================================================
gem 'hydra', '11.0.0'
gem 'nokogiri', '~> 1.7', '>= 1.7.1'

# Other Dependencies 
# =====================================================
gem 'devise'
gem 'rsolr', '~> 1.0'
gem 'devise-guests', '~> 0.5'

# Capistrano
# =====================================================
# gem 'capistrano-rails'

# DEVELOPMENT AND TESTS ONLY
# =====================================================
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'rspec-rails'
  gem 'jettywrapper'
  gem 'listen'
  gem 'solr_wrapper', '>= 0.3'
  gem 'fcrepo_wrapper'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
